//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjGeo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GeoGisEntities : DbContext
    {
        public GeoGisEntities()
            : base("name=GeoGisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mForm> mForm { get; set; }
        public DbSet<mGISArea> mGISArea { get; set; }
        public DbSet<mMenu> mMenu { get; set; }
        public DbSet<mSharp> mSharp { get; set; }
        public DbSet<mUser> mUser { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<mGrid> mGrid { get; set; }
        public DbSet<mArea> mArea { get; set; }
        public DbSet<mElement> mElement { get; set; }
    }
}
