//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjGeo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mElementalAbundance
    {
        public int id { get; set; }
        public double AbundanceVal { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
        public string Element { get; set; }
        public string Remarks { get; set; }
    }
}
