//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjGeo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mGISArea
    {
        public int id { get; set; }
        public string ProvinceID { get; set; }
        public string ProvinceName { get; set; }
        public string ParentID { get; set; }
        public string AreaName { get; set; }
        public string AreaCode { get; set; }
        public Nullable<double> flon { get; set; }
        public Nullable<double> flat { get; set; }
        public int IsLeef { get; set; }
        public int IsVisible { get; set; }
        public int SetMarkerCnt { get; set; }
        public int SetPloyGonCnt { get; set; }
        public int SetCircleCnt { get; set; }
    }
}
