//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjGeo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mGrid
    {
        public int id { get; set; }
        public int FormID { get; set; }
        public int SeqNo { get; set; }
        public string ColName { get; set; }
        public int ColWidth { get; set; }
        public string ColAlign { get; set; }
        public string ColTitle { get; set; }
        public int ColRowspan { get; set; }
        public bool Colhidden { get; set; }
        public string ColField { get; set; }
        public string ColEditor { get; set; }
        public bool isSum { get; set; }
        public bool isAvg { get; set; }
        public bool isMax { get; set; }
        public bool isMin { get; set; }
        public bool isSort { get; set; }
        public bool isUsed { get; set; }
    }
}
