//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjGeo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mKml
    {
        public int id { get; set; }
        public string ProvinceName { get; set; }
        public string CityName { get; set; }
        public string CountyName { get; set; }
        public string TownName { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<int> IsVisible { get; set; }
        public string KmlPath { get; set; }
        public string LayerName { get; set; }
        public string VillageName { get; set; }
        public Nullable<int> LayerOrder { get; set; }
        public string ProjId { get; set; }
        public string PrjName { get; set; }
    }
}
