//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjGeo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mKml
    {
        public string id { get; set; }
        public string provinceName { get; set; }
        public string cityName { get; set; }
        public string countyName { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<int> isVisible { get; set; }
        public string kmlPath { get; set; }
        public string layerName { get; set; }
        public string villageName { get; set; }
        public Nullable<int> layerOrder { get; set; }
        public string projId { get; set; }
        public string prjName { get; set; }
    }
}
