//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjGeo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mMenu
    {
        public int id { get; set; }
        public string MenuID { get; set; }
        public string ParentID { get; set; }
        public string MenuName { get; set; }
        public string mURL { get; set; }
        public int IsLeef { get; set; }
        public string IconClass { get; set; }
        public string MenuDesc { get; set; }
        public int MenuSeqNo { get; set; }
        public int IsVisible { get; set; }
        public int mState { get; set; }
        public int mChecked { get; set; }
        public int RightFlag { get; set; }
    }
}
