//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjGeo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mProject
    {
        public int id { get; set; }
        public Nullable<int> Recid { get; set; }
        public string Ccode { get; set; }
        public string CName { get; set; }
        public string Clocation { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string Town { get; set; }
        public string Village { get; set; }
        public string Remarks { get; set; }
    }
}
