//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjGeo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mSharp
    {
        public int id { get; set; }
        public string SharpID { get; set; }
        public string SharpName { get; set; }
        public double flat { get; set; }
        public double flon { get; set; }
    }
}
