//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjGeo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mZone
    {
        public int id { get; set; }
        public int Recid { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string Town { get; set; }
        public string Village { get; set; }
        public string MapNumber { get; set; }
        public string SampleNumber { get; set; }
        public string ProCode { get; set; }
        public Nullable<double> CSYSX { get; set; }
        public Nullable<double> CSYSY { get; set; }
        public string CSYSType { get; set; }
        public Nullable<double> Flon { get; set; }
        public Nullable<double> Flat { get; set; }
        public string Cale { get; set; }
        public string SampleNo { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
        public string Remarks { get; set; }
    }
}
